#!/usr/bin/env node
// Refresh ONLY the ToC in assets/styles.css.
// Scans existing SECTION markers, rebuilds the ToC block in place.
// Use after content edits that change line numbers (e.g. dead selector apply).

const fs = require('fs');
const CSS = 'assets/styles.css';
const raw = fs.readFileSync(CSS, 'utf8');
const EOL = raw.includes('\r\n') ? '\r\n' : '\n';
const lines = raw.split(/\r?\n/);

// Locate existing ToC bounds.
let tocStart = -1, tocEnd = -1;
for (let i = 0; i < Math.min(80, lines.length); i++) {
  if (lines[i].includes('TABLE OF CONTENTS')) {
    for (let s = i; s >= 0; s--) {
      if (lines[s].includes('╔')) { tocStart = s; break; }
    }
    for (let e = i; e < lines.length; e++) {
      if (lines[e].includes('╝')) { tocEnd = e; break; }
    }
    break;
  }
}
if (tocStart === -1 || tocEnd === -1) {
  console.error('ToC not found — refresh requires existing ToC block.');
  process.exit(1);
}
const oldTocLen = tocEnd - tocStart + 1;

// Scan SECTION markers (find their actual current positions).
const markerRe = /^\s*SECTION (\d+) — (.+?)\s*$/;
const entries = [];
for (let i = 0; i < lines.length; i++) {
  if (i >= tocStart && i <= tocEnd) continue; // skip ToC region itself
  const m = lines[i].match(markerRe);
  if (m) entries.push({ id: m[1], title: m[2], line: i + 1 });
}
entries.sort((a, b) => a.id.localeCompare(b.id));

// Build new ToC content.
const newToc = [
  '/* ╔═══════════════════════════════════════════════════════════════════╗',
  '     TABLE OF CONTENTS — Ctrl+F "SECTION NN" でジャンプ',
  '     (auto-generated by scripts/add-section-markers.cjs)',
  '   ───────────────────────────────────────────────────────────────────',
];
const footerToc = ['   ╚═══════════════════════════════════════════════════════════════════╝ */'];
const newTocLen = newToc.length + entries.length + footerToc.length;
const SHIFT = newTocLen - oldTocLen;
for (const e of entries) {
  const lineStr = String(e.line + SHIFT).padStart(5, ' ');
  newToc.push(`     SECTION ${e.id} — ${e.title.padEnd(38, ' ')} L${lineStr}`);
}
newToc.push(...footerToc);

lines.splice(tocStart, oldTocLen, ...newToc);
fs.writeFileSync(CSS, lines.join(EOL), 'utf8');
console.log(`Refreshed ToC: ${entries.length} entries, shift=${SHIFT} (old=${oldTocLen} → new=${newTocLen} lines).`);
